# Generated by Django 5.1.1 on 2024-10-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='task_images/'),
        ),
    ]
