# Generated by Django 5.1.1 on 2024-10-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to='task_images/'),
        ),
    ]
